import React from 'react';
import { User, Channel, UserRole, PostType, ChannelMessage, Notification, DirectMessage, Section, Gender } from './types';

export const UNIVERSITIES = [
    "جامعة ابن خلدون تيارت",
    "ملحقة جامعة تيارت بقصر الشلالة",
    "جامعة الجزائر 1 - بن يوسف بن خدة",
    "جامعة الجزائر 2 - أبو القاسم سعد الله",
    "جامعة الجزائر 3 - إبراهيم سلطان شيبوط",
    "جامعة العلوم والتكنولوجيا هواري بومدين (باب الزوار)",
    "جامعة سعد دحلب (البليدة 1)",
    "جامعة علي لونيسي (البليدة 2)",
    "جامعة يحيى فارس (المدية)",
    "جامعة امحمد بوقرة (بومرداس)",
    "جامعة آكلي محند أولحاج (البويرة)",
    "جامعة الجيلالي بونعامة (خميس مليانة)",
];

export const COLLEGES = [
    "كلية العلوم والعلوم التطبيقية",
    "كلية التكنولوجيا",
    "كلية علوم الطبيعة والحياة",
    "كلية الطب",
    "كلية الحقوق والعلوم السياسية",
    "كلية العلوم الاقتصادية والتجارية وعلوم التسيير",
    "كلية الآداب واللغات",
    "كلية العلوم الإنسانية والاجتماعية",
];

export const MOCK_PROFESSOR: User = {
    id: 'prof-1',
    name: 'بن الطاهر بختة',
    email: 'bekhta@univ-ibnkhaldoun.dz',
    role: UserRole.Professor,
    gender: Gender.Female,
    university: 'ملحقة جامعة تيارت بقصر الشلالة',
    college: 'كلية العلوم الاقتصادية والتجارية وعلوم التسيير',
    avatar: 'https://picsum.photos/seed/prof2/200',
    subscribedSections: [],
};

export const MOCK_STUDENT: User = {
    id: 'student-1',
    name: 'حمر العين ربيع',
    email: 'rabie@student.dz',
    role: UserRole.Student,
    gender: Gender.Male,
    university: 'ملحقة جامعة تيارت بقصر الشلالة',
    college: 'كلية العلوم الاقتصادية والتجارية وعلوم التسيير',
    avatar: 'https://picsum.photos/seed/student2/200',
    subscribedSections: ['sec-1'],
    phoneNumber: '+213987654321',
};

export const MOCK_STUDENT_2: User = {
    id: 'student-2',
    name: 'علي أحمد',
    email: 'ali@student.dz',
    role: UserRole.Student,
    gender: Gender.Male,
    university: 'جامعة ابن خلدون تيارت',
    college: 'كلية الحقوق والعلوم السياسية',
    avatar: 'https://picsum.photos/seed/student3/200',
    subscribedSections: ['sec-2'], // Subscribed to ch-1
    phoneNumber: '',
};

export const MOCK_STUDENT_3: User = {
    id: 'student-3',
    name: 'فاطمة الزهراء',
    email: 'fatima@student.dz',
    role: UserRole.Student,
    gender: Gender.Female,
    university: 'ملحقة جامعة تيارت بقصر الشلالة',
    college: 'كلية العلوم الاقتصادية والتجارية وعلوم التسيير',
    avatar: 'https://picsum.photos/seed/student4/200',
    subscribedSections: ['sec-1', 'sec-3'], // Subscribed to ch-1 and ch-2
    phoneNumber: '',
};

export const MOCK_ALL_USERS = [MOCK_PROFESSOR, MOCK_STUDENT, MOCK_STUDENT_2, MOCK_STUDENT_3];

export const MOCK_CHANNELS: Channel[] = [
    {
        id: 'ch-1',
        name: 'الرياضيات المالية',
        specialization: 'مالية و بنوك',
        professorId: 'prof-1',
        meetLink: 'https://meet.google.com/new',
        posts: [
            { id: 'p-1', type: PostType.PDF, title: 'محاضرة 1 - مقدمة.pdf', url: 'https://www.actuarialfoundation.org/wp-content/uploads/2019/07/AF-Financial-Literacy-Middle-School-final-webletters-compressed.pdf', createdAt: '2024-05-20' },
            { id: 'p-2', type: PostType.Image, title: 'رسم بياني للفائدة المركبة.png', url: 'https://picsum.photos/seed/proc/800/400', createdAt: '2024-05-21' },
            { id: 'p-3', type: PostType.Video, title: 'فيديو: شرح الخصم', url: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4', createdAt: '2024-05-22' },
        ],
        subscribers: 23,
        blockedUsers: [],
    },
    {
        id: 'ch-2',
        name: 'مبادئ الاقتصاد الجزئي',
        specialization: 'علوم اقتصادية',
        professorId: 'prof-1',
        meetLink: 'https://meet.google.com/new',
        posts: [
             { id: 'p-4', type: PostType.PDF, title: 'منهج المقرر.pdf', url: '#', createdAt: '2024-05-19' },
        ],
        subscribers: 15,
        blockedUsers: [],
    }
];

export const MOCK_SECTIONS: Section[] = [
    { id: 'sec-1', name: 'الفصل الأول: الفائدة البسيطة والمركبة', channelId: 'ch-1', price: 100 },
    { id: 'sec-2', name: 'الفصل الثاني: الدفعات', channelId: 'ch-1', price: 100 },
    { id: 'sec-3', name: 'المدخل إلى علم الاقتصاد', channelId: 'ch-2', price: 100 },
];

export const MOCK_CHANNEL_MESSAGES: ChannelMessage[] = [
    { id: 'msg-ch-1', senderId: 'prof-1', channelId: 'ch-1', text: 'Welcome to the channel! Please review the syllabus.', timestamp: '10:00 AM' },
    { id: 'msg-ch-2', senderId: 'student-1', channelId: 'ch-1', text: 'Thank you, professor!', timestamp: '10:01 AM' },
];

export const MOCK_DIRECT_MESSAGES: DirectMessage[] = [
    { id: 'dm-1', senderId: 'student-1', receiverId: 'prof-1', text: 'السلام عليكم أستاذة، لدي سؤال بخصوص المحاضرة الأخيرة.', timestamp: '11:30 AM' },
    { id: 'dm-2', senderId: 'prof-1', receiverId: 'student-1', text: 'وعليكم السلام، تفضل بالطبع.', timestamp: '11:32 AM' },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
    { id: 'notif-1', text: 'تم إضافة منشور جديد في قناة "الرياضيات المالية".', timestamp: 'منذ 5 دقائق', read: false },
    { id: 'notif-2', text: 'سيبدأ اجتماع Google Meet لقناة "مبادئ الاقتصاد الجزئي" قريبًا.', timestamp: 'منذ ساعة', read: false },
    { id: 'notif-3', text: 'قام الطالب "حمر العين ربيع" بإرسال رسالة مباشرة.', timestamp: 'منذ 3 ساعات', read: true },
];

export const APP_URL = 'https://way-4.vercel.app/';
export const QR_CODE_DATA_URL = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOQAAAEgCAYAAAD2/h5GAAABwElEQVR4nO3bQQ3AMAzAsIL/o212g1YgQcT7A2+eD/C67gMExIAYECMCAWJADIgRgQAxIAZEgsSAGBBjAgFigAxIkRgQA2JEIEAMiAGRIDFgBswbYMAYECMCAWJADIgRgQAxIAZEgsSAGBBjAgFigAxIkRgQA2JEIEAMiAGRIDFgBsyAGBADIgRigAxIAZEjMAEJEAMiRGBAD сантиметраAZEgNiQIzJgBgQA2JEIEAMiAGRIDFgBswbYMAYECMCAWJADIgRgQAxIAZEgsSAGBBjAgFigAxIkRgQA2JEIEAMiAGRIDFgBsyAGBADIgRigAxIAZEjMAEJEAMiRGBAD сантиметраAZEgNiQIzJgBgQA2JEIEAMiAGRIDFgBswbYMAYECMCAWJADIgRgQAxIAZEgsSAGBBjAgFigAxIkRgQA2JEIEAMiAGRIDFgBsyAGBADIgRigAxIAZEjMAEJEAMiRGBAD сантиметраAZEgNiQIzJgBgQA2JEIEAMiAGRIDFgBswbYMAYECMCAWJADIgRgQAxIAZEgsSAGBBjAgFigAxIkRgQA2JEIEAMiAGRIDFgBsyAGBADIgRigAxIAZEjMAEJEAMiRGBAD сантиметраAZEgNiQIzJgBgQA2JEIEAMiAGRIDFgBswbYMAYECMCAWJADIgRgQAxIAZEgsSAGBBjAgFigAxIkRgQA2JEIEAMiAGRIDFgBsyAGBADIgRigAxIAZEjMAEJEAMiRGBAD сантиметраAZEgNiQIzJgBgQA2JEIH/AAL2bghA7o7pUAAAAABJRU5ErkJggg==';


export const STRINGS = {
    ar: {
        appName: 'جامعتك الرقمية way',
        login: 'تسجيل الدخول',
        register: 'إنشاء حساب',
        email: 'البريد الإلكتروني',
        password: 'كلمة المرور',
        fullName: 'الاسم الكامل',
        role: 'الدور',
        gender: 'الجنس',
        male: 'ذكر',
        female: 'أنثى',
        professor: 'أستاذ',
        student: 'طالب',
        professorMaleTitle: 'الأستاذ',
        professorFemaleTitle: 'الأستاذة',
        studentMaleTitle: 'الطالب',
        studentFemaleTitle: 'الطالبة',
        university: 'الجامعة',
        college: 'الكلية',
        select: 'اختر...',
        submit: 'إرسال',
        myChannels: 'قنواتي',
        createChannel: 'إنشاء قناة',
        profileSettings: 'إعدادات الملف الشخصي',
        logout: 'تسجيل الخروج',
        darkMode: 'الوضع الليلي',
        lightMode: 'الوضع النهاري',
        language: 'اللغة',
        channelName: 'اسم القناة',
        specialization: 'التخصص',
        close: 'إغلاق',
        save: 'حفظ',
        subscribe: 'اشتراك',
        subscribed: 'مشترك',
        subscriptionTitle: 'تأكيد الاشتراك',
        subscriptionMessage: 'الاشتراك في هذه القناة سيكلف 100 دج لمدة 3 أشهر. يمكنك الانضمام مجاناً حتى يتم تفعيل الميزة.',
        sectionSubscriptionMessage: 'الاشتراك في هذا القسم سيكلف {price} دج لمدة 3 أشهر. يمكنك الانضمام مجاناً حتى يتم تفعيل الميزة.',
        subscriptionSuccessNotification: 'تم اشتراكك بنجاح في قسم "{sectionName}" في قناة "{channelName}".',
        confirm: 'تأكيد',
        cancel: 'إلغاء',
        posts: 'المنشورات',
        chat: 'دردشة',
        googleMeet: 'انضم إلى Google Meet',
        upload: 'رفع ملف',
        typeMessage: 'اكتب رسالتك...',
        demoStudent: 'طالب تجريبي',
        demoProfessor: 'أستاذ تجريبي',
        orTryDemo: 'أو جرب حسابًا تجريبيًا',
        back: 'العودة',
        explore: 'استكشاف',
        openChannel: 'عرض القناة',
        jarvisAi: 'جارفيس AI',
        jarvisDescription: "أنا جارفيس، مساعدك الذكي في منصة 'جامعتك الرقمية way'. أقدم استشارات أكاديمية للطلاب بالاعتماد على مصادر البحث الجزائرية، وعلى رأسها منصة ASJP.",
        askJarvis: 'اسأل جارفيس...',
        welcomeBack: 'مرحباً بعودتك،',
        welcomeGreetingMale: 'مرحباً بك',
        welcomeGreetingFemale: 'مرحباً بكِ',
        notifications: 'الإشعارات',
        noNotifications: 'لا توجد إشعارات جديدة.',
        directMessages: 'الرسائل المباشرة',
        asjpPlatform: 'منصة ASJP',
        phoneNumber: 'رقم الهاتف',
        phoneNumberDescription: 'يستخدم لسحب الرصيد.',
        shareApp: 'مشاركة التطبيق',
        scanToOpen: 'امسح الرمز لفتح التطبيق على جهاز آخر.',
        appUrl: 'رابط التطبيق',
        installApp: 'اضف التطبيق الى شاشتك',
        installAppDescription: 'مرحبا بك في جامعتك الرقمية',
        install: 'تثبيت',
        later: 'لاحقاً',
        clearChat: 'محو المحادثة',
        clearChatConfirmTitle: 'تأكيد محو المحادثة',
        clearChatConfirmMessage: 'هل أنت متأكد أنك تريد محو سجل المحادثة بالكامل لهذه القناة؟ هذا الإجراء لا يمكن التراجع عنه وسيحذف المحادثة للجميع.',
        deletePost: 'حذف المنشور',
        deletePostConfirmTitle: 'تأكيد الحذف',
        deletePostConfirmMessage: 'هل أنت متأكد أنك تريد حذف هذا المنشور؟ لا يمكن التراجع عن هذا الإجراء.',
        downloadForOffline: 'تنزيل للعرض بدون انترنت',
        downloaded: 'تم التنزيل',
        removeFromOffline: 'إزالة من التنزيلات',
        termsAndConditions: "شروط وأحكام الاستخدام",
        agree: "أوافق",
        professorCharterTitle: "ميثاق الأستاذ",
        professorCharterRules: [
            "الاستقلالية التامة: الأستاذ هو المسؤول الوحيد عن صحة وجودة ما ينشره لطلبته في قناته الخاصة.",
            "الإدارة الذاتية: الالتزام بإدارة مساحات النقاش وتصفيرها لضمان بقاء البيئة تعليمية ومنضبطة.",
            "الأمانة الأكاديمية: استخدام المنصة لنشر المحتوى العلمي الذي يخدم المسار الدراسي فقط.",
            "القبول التقني: الموافقة على أن دور المنصة هو توفير 'الوسيلة' التقنية للربط بينه وبين الطلبة."
        ],
        studentCharterTitle: "ميثاق الطالب",
        studentCharterRules: [
            "الوقار الرقمي: الالتزام بالأدب في الدردشة، فأي تجاوز يعرضك للحظر الفوري من قِبل الأستاذ.",
            "الاستعمال العادل: المنصة للبحث العلمي فقط؛ يمنع استغلالها في أي تواصل خارج هذا الإطار.",
            "احترام الخصوصية: يُمنع محاولة تصوير أو نشر بيانات الزملاء أو الأساتذة خارج المنصة.",
            "الموافقة التقنية: الإقرار بأن المنصة توفر الأدوات، وأن مسؤولية التفاعل تقع على عاتق المستخدم."
        ],
        subscribers: 'المشتركون',
        block: 'حظر',
        message: 'مراسلة',
        blockUserConfirmTitle: 'تأكيد الحظر',
        blockUserConfirmMessage: 'هل أنت متأكد أنك تريد حظر {userName} من هذه القناة؟ سيفقد الوصول إلى كل المحتوى والدردشة.',
        channelsBy: 'قنوات الأستاذ {profName}',
        channels: 'قنوات',
        noProfessorsFound: 'لم يتم العثور على أساتذة في الجامعة والكلية المحددة.',
        noSubscribedChannels: "أنت غير مشترك في أي قناة بعد",
        noSubscribedChannelsHint: "استخدم قسم 'استكشاف' للعثور على القنوات والانضمام إليها.",
        addFileOr: 'اسحب وأفلت أو',
        addLinkPost: 'إضافة منشور كرابط',
        addLinkPostDescription: 'مشاركة رابط من الويب.',
        postLinkTitle: 'إضافة منشور كرابط',
        postTitleLabel: 'عنوان المنشور',
        postUrlLabel: 'الرابط',
        largeFileTitle: 'الملف كبير جدًا',
        largeFileWarningTitle: 'الملف كبير جدًا',
        largeFileWarningMessage1: '"{fileName}" ({fileSize} ميغابايت) يتجاوز حد 30 ميغابايت للرفع المباشر.',
        largeFileWarningMessage2: 'الرجاء رفع الملف إلى خدمة سحابية (مثل Google Drive) ولصق رابط المشاركة العام أدناه.',
    },
    en: {
        appName: 'Your Digital University Way',
        login: 'Login',
        register: 'Register',
        email: 'Email',
        password: 'Password',
        fullName: 'Full Name',
        role: 'Role',
        gender: 'Gender',
        male: 'Male',
        female: 'Female',
        professor: 'Professor',
        student: 'Student',
        university: 'University',
        college: 'College',
        select: 'Select...',
        submit: 'Submit',
        myChannels: 'My Channels',
        createChannel: 'Create Channel',
        profileSettings: 'Profile Settings',
        logout: 'Logout',
        darkMode: 'Dark Mode',
        lightMode: 'Light Mode',
        language: 'Language',
        channelName: 'Channel Name',
        specialization: 'Specialization',
        close: 'Close',
        save: 'Save',
        subscribe: 'Subscribe',
        subscribed: 'Subscribed',
        subscriptionTitle: 'Confirm Subscription',
        subscriptionMessage: 'Subscription for this channel will cost 100 DZD for 3 months. You can join for free until this feature is activated.',
        sectionSubscriptionMessage: 'Subscription for this section will cost {price} DZD for 3 months. You can join for free until this feature is activated.',
        subscriptionSuccessNotification: 'You have successfully subscribed to section "{sectionName}" in the channel "{channelName}".',
        confirm: 'Confirm',
        cancel: 'Cancel',
        posts: 'Posts',
        chat: 'Chat',
        googleMeet: 'Join Google Meet',
        upload: 'Upload File',
        typeMessage: 'Type your message...',
        demoStudent: 'Demo Student',
        demoProfessor: 'Demo Professor',
        orTryDemo: 'Or try a demo account',
        back: 'Back',
        explore: 'Explore',
        openChannel: 'Open Channel',
        jarvisAi: 'Jarvis AI',
        jarvisDescription: "I am Jarvis, your smart assistant on the 'Your Digital University Way' platform. I provide academic consultations for students, relying on Algerian research sources, especially the ASJP platform.",
        askJarvis: 'Ask Jarvis...',
        welcomeBack: 'Welcome back,',
        notifications: 'Notifications',
        noNotifications: 'No new notifications.',
        directMessages: 'Direct Messages',
        asjpPlatform: 'ASJP Platform',
        phoneNumber: 'Phone Number',
        phoneNumberDescription: 'Used for balance withdrawal.',
        shareApp: 'Share App',
        scanToOpen: 'Scan the code to open the app on another device.',
        appUrl: 'App URL',
        installApp: 'Install App',
        installAppDescription: 'Add this app to your home screen for quick access and offline use.',
        install: 'Install',
        later: 'Later',
        clearChat: 'Clear Chat',
        clearChatConfirmTitle: 'Confirm Clear Chat',
        clearChatConfirmMessage: 'Are you sure you want to clear the entire chat history for this channel? This action is irreversible and will delete the chat for everyone.',
        deletePost: 'Delete Post',
        deletePostConfirmTitle: 'Confirm Deletion',
        deletePostConfirmMessage: 'Are you sure you want to delete this post? This action cannot be undone.',
        downloadForOffline: 'Download for offline',
        downloaded: 'Downloaded',
        removeFromOffline: 'Remove from offline',
        termsAndConditions: "Terms and Conditions of Use",
        agree: "I Agree",
        professorCharterTitle: "Professor Charter",
        professorCharterRules: [
            "Complete Independence: The professor is solely responsible for the accuracy and quality of the content published to their students in their private channel.",
            "Self-Management: Commitment to managing and clearing discussion spaces to ensure a disciplined and educational environment.",
            "Academic Integrity: Using the platform to publish only scientific content that serves the academic curriculum.",
            "Technical Acceptance: Agreeing that the platform's role is to provide the technical 'means' to connect with students."
        ],
        studentCharterTitle: "Student Charter",
        studentCharterRules: [
            "Digital Decorum: Adherence to etiquette in chats; any violation will result in an immediate ban by the professor.",
            "Fair Use: The platform is for academic research only; using it for any communication outside this scope is prohibited.",
            "Respect for Privacy: Attempting to capture or publish data of colleagues or professors outside the platform is forbidden.",
            "Technical Agreement: Acknowledging that the platform provides the tools, and the responsibility for interaction lies with the user."
        ],
        subscribers: 'Subscribers',
        block: 'Block',
        message: 'Message',
        blockUserConfirmTitle: 'Confirm Block',
        blockUserConfirmMessage: 'Are you sure you want to block {userName} from this channel? They will lose access to all content and chat.',
        channelsBy: 'Channels by {profName}',
        channels: 'Channels',
        noProfessorsFound: 'No professors found for the selected university and college.',
        noSubscribedChannels: "You are not subscribed to any channels yet",
        noSubscribedChannelsHint: "Use the 'Explore' tab to find and join channels.",
        addFileOr: 'Drag & drop or',
        addLinkPost: 'Add Post as Link',
        addLinkPostDescription: 'Share a link from the web.',
        postLinkTitle: 'Add Post as Link',
        postTitleLabel: 'Post Title',
        postUrlLabel: 'Link',
        largeFileTitle: 'File is Too Large',
        largeFileWarningTitle: 'File is Too Large',
        largeFileWarningMessage1: '"{fileName}" ({fileSize} MB) exceeds the 30MB direct upload limit.',
        largeFileWarningMessage2: 'Please upload the file to a cloud service (like Google Drive) and paste the public sharing link below.',
    },
    fr: {
        appName: 'Votre Université Numérique Way',
        login: 'Connexion',
        register: 'S\'inscrire',
        email: 'Email',
        password: 'Mot de passe',
        fullName: 'Nom et Prénom',
        role: 'Rôle',
        gender: 'Genre',
        male: 'Homme',
        female: 'Femme',
        professor: 'Professeur',
        student: 'Étudiant',
        university: 'Université',
        college: 'Faculté',
        select: 'Sélectionner...',
        submit: 'Soumettre',
        myChannels: 'Mes Chaînes',
        createChannel: 'Créer une chaîne',
        profileSettings: 'Paramètres du profil',
        logout: 'Déconnexion',
        darkMode: 'Mode Sombre',
        lightMode: 'Mode Clair',
        language: 'Langue',
        channelName: 'Nom de la chaîne',
        specialization: 'Spécialisation',
        close: 'Fermer',
        save: 'Enregistrer',
        subscribe: 'S\'abonner',
        subscribed: 'Abonné',
        subscriptionTitle: 'Confirmer l\'abonnement',
        subscriptionMessage: 'L\'abonnement à cette chaîne coûtera 100 DZD pour 3 mois. Vous pouvez rejoindre gratuitement jusqu\'à ce que cette fonctionnalité soit activée.',
        sectionSubscriptionMessage: 'L\'abonnement à cette section coûtera {price} DZD pour 3 mois. Vous pouvez rejoindre gratuitement jusqu\'à ce que cette fonctionnalité soit activée.',
        subscriptionSuccessNotification: 'Vous vous êtes abonné avec succès à la section "{sectionName}" dans la chaîne "{channelName}".',
        confirm: 'Confirmer',
        cancel: 'Annuler',
        posts: 'Publications',
        chat: 'Chat',
        googleMeet: 'Rejoindre Google Meet',
        upload: 'Téléverser',
        typeMessage: 'Tapez votre message...',
        demoStudent: 'Étudiant de démo',
        demoProfessor: 'Professeur de démo',
        orTryDemo: 'Ou essayez un compte démo',
        back: 'Retour',
        explore: 'Explorer',
        openChannel: 'Ouvrir la chaîne',
        jarvisAi: 'Jarvis AI',
        jarvisDescription: "Je suis Jarvis, votre assistant intelligent sur la plateforme 'Votre Université Numérique Way'. Je fournis des consultations académiques aux étudiants, en m'appuyant sur les sources de recherche algériennes, notamment la plateforme ASJP.",
        askJarvis: 'Demandez à Jarvis...',
        welcomeBack: 'Content de vous revoir,',
        notifications: 'Notifications',
        noNotifications: 'Aucune nouvelle notification.',
        directMessages: 'Messages Directs',
        asjpPlatform: 'Plateforme ASJP',
        phoneNumber: 'Numéro de téléphone',
        phoneNumberDescription: 'Utilisé pour le retrait du solde.',
        shareApp: 'Partager l\'application',
        scanToOpen: 'Scannez le code pour ouvrir l\'application sur un autre appareil.',
        appUrl: 'URL de l\'application',
        installApp: 'Installer l\'application',
        installAppDescription: 'Ajoutez cette application à votre écran d\'accueil pour un accès rapide et une utilisation hors ligne.',
        install: 'Installer',
        later: 'Plus tard',
        clearChat: 'Effacer le chat',
        clearChatConfirmTitle: 'Confirmer l\'effacement',
        clearChatConfirmMessage: 'Êtes-vous sûr de vouloir effacer tout l\'historique du chat pour cette chaîne ? Cette action est irréversible et supprimera le chat pour tout le monde.',
        deletePost: 'Supprimer la publication',
        deletePostConfirmTitle: 'Confirmer la suppression',
        deletePostConfirmMessage: 'Êtes-vous sûr de vouloir supprimer cette publication ? Cette action est irréversible.',
        downloadForOffline: 'Télécharger pour hors ligne',
        downloaded: 'Téléchargé',
        removeFromOffline: 'Supprimer des téléchargements',
        termsAndConditions: "Conditions d'utilisation",
        agree: "J'accepte",
        professorCharterTitle: "Charte de l'enseignant",
        professorCharterRules: [
            "Indépendance totale : L'enseignant est le seul responsable de l'exactitude et de la qualité du contenu publié pour ses étudiants sur sa chaîne privée.",
            "Autogestion : Engagement à gérer et à vider les espaces de discussion pour garantir un environnement discipliné et éducatif.",
            "Intégrité académique : Utiliser la plateforme uniquement pour publier du contenu scientifique qui sert le programme académique.",
            "Acceptation technique : Accepter que le rôle de la plateforme est de fournir le 'moyen' technique de se connecter avec les étudiants."
        ],
        studentCharterTitle: "Charte de l'étudiant",
        studentCharterRules: [
            "Bienséance numérique : Respect de l'étiquette dans les discussions ; toute infraction entraînera un bannissement immédiat par l'enseignant.",
            "Utilisation équitable : La plateforme est réservée à la recherche universitaire ; son utilisation pour toute communication hors de ce cadre est interdite.",
            "Respect de la vie privée : Il est interdit de tenter de capturer ou de publier des données de collègues ou d'enseignants en dehors de la plateforme.",
            "Accord technique : Reconnaître que la plateforme fournit les outils et que la responsabilité de l'interaction incombe à l'utilisateur."
        ],
        subscribers: 'Abonnés',
        block: 'Bloquer',
        message: 'Message',
        blockUserConfirmTitle: 'Confirmer le blocage',
        blockUserConfirmMessage: 'Êtes-vous sûr de vouloir bloquer {userName} de cette chaîne ? Il perdra l\'accès à tout le contenu et au chat.',
        channelsBy: 'Chaînes par {profName}',
        channels: 'Chaînes',
        noProfessorsFound: 'Aucun professeur trouvé pour l\'université et la faculté sélectionnées.',
        noSubscribedChannels: "Vous n'êtes abonné à aucune chaîne pour le moment",
        noSubscribedChannelsHint: "Utilisez l'onglet 'Explorer' pour trouver et rejoindre des chaînes.",
        addFileOr: 'Glissez-déposez ou',
        addLinkPost: 'Ajouter comme Lien',
        addLinkPostDescription: 'Partagez un lien depuis le web.',
        postLinkTitle: 'Ajouter comme Lien',
        postTitleLabel: 'Titre de la publication',
        postUrlLabel: 'Lien',
        largeFileTitle: 'Fichier trop volumineux',
        largeFileWarningTitle: 'Fichier trop volumineux',
        largeFileWarningMessage1: '"{fileName}" ({fileSize} Mo) dépasse la limite de téléversement direct de 30 Mo.',
        largeFileWarningMessage2: 'Veuillez téléverser le fichier sur un service cloud (comme Google Drive) et coller le lien de partage public ci-dessous.',
    }
};

export const getLang = (lang: 'ar' | 'en' | 'fr') => STRINGS[lang];