
import React from 'react';
import { User, Channel, UserRole, PostType, ChannelMessage, DirectMessage, Notification } from './types';

export const UNIVERSITIES = [
    "جامعة ابن خلدون ملحقة قصر الشلالة",
    "جامعة ابن خلدون تيارت",
    "جامعة زيان عاشور الجلفة",
    "University of Algiers 1",
    "University of Oran 1",
    "University of Constantine 1",
    "University of Science and Technology Houari Boumediene (USTHB)",
];

export const COLLEGES = [
    "كلية العلوم اقتصادية و علوم تسيير",
    "Faculty of Medicine",
    "Faculty of Law",
    "Faculty of Science",
    "Faculty of Technology",
];

export const MOCK_PROFESSOR: User = {
    id: 'prof-1',
    name: 'بن الطاهر بختة',
    email: 'bekhta@univ-ibnkhaldoun.dz',
    role: UserRole.Professor,
    university: 'جامعة ابن خلدون ملحقة قصر الشلالة',
    college: 'كلية العلوم اقتصادية و علوم تسيير',
    avatar: 'https://picsum.photos/seed/prof2/200',
    subscribedChannels: [],
};

export const MOCK_PROFESSOR_2: User = {
    id: 'prof-2',
    name: 'أستاذ تيارت',
    email: 'prof@univ-tiaret.dz',
    role: UserRole.Professor,
    university: 'جامعة ابن خلدون تيارت',
    college: 'Faculty of Technology',
    avatar: 'https://picsum.photos/seed/prof3/200',
    subscribedChannels: [],
};

export const MOCK_PROFESSOR_3: User = {
    id: 'prof-3',
    name: 'أستاذ الجلفة',
    email: 'prof@univ-djelfa.dz',
    role: UserRole.Professor,
    university: 'جامعة زيان عاشور الجلفة',
    college: 'Faculty of Science',
    avatar: 'https://picsum.photos/seed/prof4/200',
    subscribedChannels: [],
};


export const MOCK_STUDENT: User = {
    id: 'student-1',
    name: 'حمر العين ربيع',
    email: 'rabie@student.dz',
    role: UserRole.Student,
    university: 'جامعة ابن خلدون ملحقة قصر الشلالة',
    college: 'كلية العلوم اقتصادية و علوم تسيير',
    avatar: 'https://picsum.photos/seed/student2/200',
    subscribedChannels: ['ch-1'],
};

export const MOCK_ALL_USERS = [MOCK_PROFESSOR, MOCK_PROFESSOR_2, MOCK_PROFESSOR_3, MOCK_STUDENT];

export const MOCK_CHANNELS: Channel[] = [
    {
        id: 'ch-1',
        name: 'الرياضيات المالية',
        specialization: 'مالية و بنوك',
        professorId: 'prof-1',
        meetLink: 'https://meet.google.com/new',
        subscribers: 23,
        posts: [
            { id: 'p-1', type: PostType.PDF, title: 'محاضرة 1 - مقدمة.pdf', url: '#', createdAt: '2024-05-20' },
            { id: 'p-2', type: PostType.Image, title: 'رسم بياني للفائدة المركبة.png', url: 'https://picsum.photos/seed/proc/800/400', createdAt: '2024-05-21' },
            { id: 'p-3', type: PostType.Video, title: 'فيديو: شرح الخصم', url: '#', createdAt: '2024-05-22' },
        ],
    },
    {
        id: 'ch-2',
        name: 'مبادئ الاقتصاد الجزئي',
        specialization: 'علوم اقتصادية',
        professorId: 'prof-1',
        meetLink: 'https://meet.google.com/new',
        subscribers: 15,
        posts: [
             { id: 'p-4', type: PostType.PDF, title: 'منهج المقرر.pdf', url: '#', createdAt: '2024-05-19' },
        ],
    },
     {
        id: 'ch-3',
        name: 'Thermodynamics',
        specialization: 'Mechanical Engineering',
        professorId: 'prof-2',
        meetLink: 'https://meet.google.com/new',
        subscribers: 45,
        posts: [
             { id: 'p-5', type: PostType.PDF, title: 'Chapter 1: Basic Concepts.pdf', url: '#', createdAt: '2024-05-18' },
        ],
    },
      {
        id: 'ch-4',
        name: 'Organic Chemistry',
        specialization: 'Chemistry',
        professorId: 'prof-3',
        meetLink: 'https://meet.google.com/new',
        subscribers: 32,
        posts: [
             { id: 'p-6', type: PostType.PDF, title: 'Lab Safety Rules.pdf', url: '#', createdAt: '2024-05-17' },
        ],
    },
];

export const MOCK_CHANNEL_MESSAGES: ChannelMessage[] = [
    { id: 'msg-ch-1', senderId: 'prof-1', channelId: 'ch-1', text: 'Welcome to the channel! Please review the syllabus.', timestamp: '10:00 AM' },
    { id: 'msg-ch-2', senderId: 'student-1', channelId: 'ch-1', text: 'Thank you, professor!', timestamp: '10:01 AM' },
    { id: 'msg-ch-3', senderId: 'student-2', channelId: 'ch-1', text: 'I have a question about the first assignment.', timestamp: '10:05 AM' },
];

export const MOCK_DMS: DirectMessage[] = [
     { id: 'msg-dm-1', senderId: 'student-1', receiverId: 'prof-1', text: 'Professor, I need an extension for the project.', timestamp: 'Yesterday' },
     { id: 'msg-dm-2', senderId: 'prof-1', receiverId: 'student-1', text: 'Please send me an email with your justification.', timestamp: 'Today' },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
    { id: 'notif-1', text: 'تم إضافة منشور جديد في قناة "الرياضيات المالية".', timestamp: 'منذ 5 دقائق', read: false },
    { id: 'notif-2', text: 'سيبدأ اجتماع Google Meet لقناة "مبادئ الاقتصاد الجزئي" قريبًا.', timestamp: 'منذ ساعة', read: false },
    { id: 'notif-3', text: 'قام الطالب "حمر العين ربيع" بإرسال رسالة مباشرة.', timestamp: 'منذ 3 ساعات', read: true },
];


export const STRINGS = {
    ar: {
        appName: 'جامعتك الرقمية way',
        login: 'تسجيل الدخول',
        register: 'إنشاء حساب',
        email: 'البريد الإلكتروني',
        password: 'كلمة المرور',
        role: 'الدور',
        professor: 'أستاذ',
        student: 'طالب',
        university: 'الجامعة',
        college: 'الكلية',
        select: 'اختر...',
        submit: 'إرسال',
        myChannels: 'قنواتي',
        createChannel: 'إنشاء قناة',
        directMessages: 'الرسائل المباشرة',
        profileSettings: 'إعدادات الملف الشخصي',
        logout: 'تسجيل الخروج',
        darkMode: 'الوضع الليلي',
        lightMode: 'الوضع النهاري',
        language: 'اللغة',
        channelName: 'اسم القناة',
        specialization: 'التخصص',
        close: 'إغلاق',
        save: 'حفظ',
        subscribe: 'اشتراك',
        subscribed: 'مشترك',
        subscriptionTitle: 'تأكيد الاشتراك',
        subscriptionMessage: 'هل تريد الاشتراك في هذه القناة مقابل 100 دج؟ سيتم خصم المبلغ من رصيد هاتفك.',
        confirm: 'تأكيد',
        cancel: 'إلغاء',
        posts: 'المنشورات',
        chat: 'دردشة',
        googleMeet: 'انضم إلى Google Meet',
        upload: 'رفع ملف',
        typeMessage: 'اكتب رسالتك...',
        demoStudent: 'طالب تجريبي',
        demoProfessor: 'أستاذ تجريبي',
        orTryDemo: 'أو جرب حسابًا تجريبيًا',
        back: 'العودة',
        explore: 'استكشاف',
        jarvisAi: 'جارفيس AI',
        jarvisDescription: 'أنا جارفيس، مساعدك الذكي. يمكنني الإجابة على أسئلتك بالاعتماد على المجلات العلمية الجزائرية أولاً، ثم المصادر العالمية.',
        askJarvis: 'اسأل جارفيس...',
        welcomeBack: 'مرحباً بعودتك،',
        notifications: 'الإشعارات',
        noNotifications: 'لا توجد إشعارات جديدة.',
    },
    en: {
        appName: 'Your Digital University Way',
        login: 'Login',
        register: 'Register',
        email: 'Email',
        password: 'Password',
        role: 'Role',
        professor: 'Professor',
        student: 'Student',
        university: 'University',
        college: 'College',
        select: 'Select...',
        submit: 'Submit',
        myChannels: 'My Channels',
        createChannel: 'Create Channel',
        directMessages: 'Direct Messages',
        profileSettings: 'Profile Settings',
        logout: 'Logout',
        darkMode: 'Dark Mode',
        lightMode: 'Light Mode',
        language: 'Language',
        channelName: 'Channel Name',
        specialization: 'Specialization',
        close: 'Close',
        save: 'Save',
        subscribe: 'Subscribe',
        subscribed: 'Subscribed',
        subscriptionTitle: 'Confirm Subscription',
        subscriptionMessage: 'Subscribe to this channel for 100 DZD? The amount will be deducted from your phone balance.',
        confirm: 'Confirm',
        cancel: 'Cancel',
        posts: 'Posts',
        chat: 'Chat',
        googleMeet: 'Join Google Meet',
        upload: 'Upload File',
        typeMessage: 'Type your message...',
        demoStudent: 'Demo Student',
        demoProfessor: 'Demo Professor',
        orTryDemo: 'Or try a demo account',
        back: 'Back',
        explore: 'Explore',
        jarvisAi: 'Jarvis AI',
        jarvisDescription: 'I am Jarvis, your smart assistant. I can answer your questions based on Algerian scientific journals first, then global sources.',
        askJarvis: 'Ask Jarvis...',
        welcomeBack: 'Welcome back,',
        notifications: 'Notifications',
        noNotifications: 'No new notifications.',
    },
    fr: {
        appName: 'Votre Université Numérique Way',
        login: 'Connexion',
        register: 'S\'inscrire',
        email: 'Email',
        password: 'Mot de passe',
        role: 'Rôle',
        professor: 'Professeur',
        student: 'Étudiant',
        university: 'Université',
        college: 'Faculté',
        select: 'Sélectionner...',
        submit: 'Soumettre',
        myChannels: 'Mes Chaînes',
        createChannel: 'Créer une chaîne',
        directMessages: 'Messages Directs',
        profileSettings: 'Paramètres du profil',
        logout: 'Déconnexion',
        darkMode: 'Mode Sombre',
        lightMode: 'Mode Clair',
        language: 'Langue',
        channelName: 'Nom de la chaîne',
        specialization: 'Spécialisation',
        close: 'Fermer',
        save: 'Enregistrer',
        subscribe: 'S\'abonner',
        subscribed: 'Abonné',
        subscriptionTitle: 'Confirmer l\'abonnement',
        subscriptionMessage: 'S\'abonner à cette chaîne pour 100 DZD? Le montant sera déduit de votre solde téléphonique.',
        confirm: 'Confirmer',
        cancel: 'Annuler',
        posts: 'Publications',
        chat: 'Chat',
        googleMeet: 'Rejoindre Google Meet',
        upload: 'Téléverser',
        typeMessage: 'Tapez votre message...',
        demoStudent: 'Étudiant de démo',
        demoProfessor: 'Professeur de démo',
        orTryDemo: 'Ou essayez un compte démo',
        back: 'Retour',
        explore: 'Explorer',
        jarvisAi: 'Jarvis AI',
        jarvisDescription: 'Je suis Jarvis, votre assistant intelligent. Je peux répondre à vos questions en me basant d\'abord sur les revues scientifiques algériennes, puis sur les sources mondiales.',
        askJarvis: 'Demandez à Jarvis...',
        welcomeBack: 'Content de vous revoir,',
        notifications: 'Notifications',
        noNotifications: 'Aucune nouvelle notification.',
    }
};

export const getLang = (lang: 'ar' | 'en' | 'fr') => STRINGS[lang];